/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppBacktestRouteImport } from './routes/app.backtest'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppExecutionReportsRouteImport } from './routes/app.execution-reports'
import { Route as AppExposureRouteImport } from './routes/app.exposure'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppIpoRouteImport } from './routes/app.ipo'
import { Route as AppKillSwitchRouteImport } from './routes/app.kill-switch'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppMonitorRouteImport } from './routes/app.monitor'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppPositionsRouteImport } from './routes/app.positions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppScannerRouteImport } from './routes/app.scanner'
import { Route as AppStrategiesRouteImport } from './routes/app.strategies'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppTradeJournalRouteImport } from './routes/app.trade-journal'
import { Route as AppWatchlistRouteImport } from './routes/app.watchlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppBacktestRoute = AppBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionReportsRoute = AppExecutionReportsRouteImport.update({
  id: '/execution-reports',
  path: '/execution-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppExposureRoute = AppExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppIpoRoute = AppIpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => AppRoute,
} as any)
const AppKillSwitchRoute = AppKillSwitchRouteImport.update({
  id: '/kill-switch',
  path: '/kill-switch',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesRoute = AppStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeJournalRoute = AppTradeJournalRouteImport.update({
  id: '/trade-journal',
  path: '/trade-journal',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/backtest': typeof AppBacktestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/execution-reports': typeof AppExecutionReportsRoute
  '/app/exposure': typeof AppExposureRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/ipo': typeof AppIpoRoute
  '/app/kill-switch': typeof AppKillSwitchRoute
  '/app/live': typeof AppLiveRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/positions': typeof AppPositionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/strategies': typeof AppStrategiesRoute
  '/app/support': typeof AppSupportRoute
  '/app/trade-journal': typeof AppTradeJournalRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/backtest': typeof AppBacktestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/execution-reports': typeof AppExecutionReportsRoute
  '/app/exposure': typeof AppExposureRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/ipo': typeof AppIpoRoute
  '/app/kill-switch': typeof AppKillSwitchRoute
  '/app/live': typeof AppLiveRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/positions': typeof AppPositionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/strategies': typeof AppStrategiesRoute
  '/app/support': typeof AppSupportRoute
  '/app/trade-journal': typeof AppTradeJournalRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/backtest': typeof AppBacktestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/execution-reports': typeof AppExecutionReportsRoute
  '/app/exposure': typeof AppExposureRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/ipo': typeof AppIpoRoute
  '/app/kill-switch': typeof AppKillSwitchRoute
  '/app/live': typeof AppLiveRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/positions': typeof AppPositionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/strategies': typeof AppStrategiesRoute
  '/app/support': typeof AppSupportRoute
  '/app/trade-journal': typeof AppTradeJournalRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/payment-failed'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/app/admin'
    | '/app/alerts'
    | '/app/backtest'
    | '/app/dashboard'
    | '/app/execution-reports'
    | '/app/exposure'
    | '/app/insights'
    | '/app/ipo'
    | '/app/kill-switch'
    | '/app/live'
    | '/app/monitor'
    | '/app/performance'
    | '/app/portfolio'
    | '/app/positions'
    | '/app/profile'
    | '/app/reports'
    | '/app/scanner'
    | '/app/strategies'
    | '/app/support'
    | '/app/trade-journal'
    | '/app/watchlist'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/payment-failed'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/app/admin'
    | '/app/alerts'
    | '/app/backtest'
    | '/app/dashboard'
    | '/app/execution-reports'
    | '/app/exposure'
    | '/app/insights'
    | '/app/ipo'
    | '/app/kill-switch'
    | '/app/live'
    | '/app/monitor'
    | '/app/performance'
    | '/app/portfolio'
    | '/app/positions'
    | '/app/profile'
    | '/app/reports'
    | '/app/scanner'
    | '/app/strategies'
    | '/app/support'
    | '/app/trade-journal'
    | '/app/watchlist'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/payment-failed'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/app/admin'
    | '/app/alerts'
    | '/app/backtest'
    | '/app/dashboard'
    | '/app/execution-reports'
    | '/app/exposure'
    | '/app/insights'
    | '/app/ipo'
    | '/app/kill-switch'
    | '/app/live'
    | '/app/monitor'
    | '/app/performance'
    | '/app/portfolio'
    | '/app/positions'
    | '/app/profile'
    | '/app/reports'
    | '/app/scanner'
    | '/app/strategies'
    | '/app/support'
    | '/app/trade-journal'
    | '/app/watchlist'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backtest': {
      id: '/app/backtest'
      path: '/backtest'
      fullPath: '/app/backtest'
      preLoaderRoute: typeof AppBacktestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/execution-reports': {
      id: '/app/execution-reports'
      path: '/execution-reports'
      fullPath: '/app/execution-reports'
      preLoaderRoute: typeof AppExecutionReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exposure': {
      id: '/app/exposure'
      path: '/exposure'
      fullPath: '/app/exposure'
      preLoaderRoute: typeof AppExposureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ipo': {
      id: '/app/ipo'
      path: '/ipo'
      fullPath: '/app/ipo'
      preLoaderRoute: typeof AppIpoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kill-switch': {
      id: '/app/kill-switch'
      path: '/kill-switch'
      fullPath: '/app/kill-switch'
      preLoaderRoute: typeof AppKillSwitchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitor': {
      id: '/app/monitor'
      path: '/monitor'
      fullPath: '/app/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/positions': {
      id: '/app/positions'
      path: '/positions'
      fullPath: '/app/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scanner': {
      id: '/app/scanner'
      path: '/scanner'
      fullPath: '/app/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategies': {
      id: '/app/strategies'
      path: '/strategies'
      fullPath: '/app/strategies'
      preLoaderRoute: typeof AppStrategiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trade-journal': {
      id: '/app/trade-journal'
      path: '/trade-journal'
      fullPath: '/app/trade-journal'
      preLoaderRoute: typeof AppTradeJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBacktestRoute: typeof AppBacktestRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExecutionReportsRoute: typeof AppExecutionReportsRoute
  AppExposureRoute: typeof AppExposureRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppIpoRoute: typeof AppIpoRoute
  AppKillSwitchRoute: typeof AppKillSwitchRoute
  AppLiveRoute: typeof AppLiveRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScannerRoute: typeof AppScannerRoute
  AppStrategiesRoute: typeof AppStrategiesRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTradeJournalRoute: typeof AppTradeJournalRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBacktestRoute: AppBacktestRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExecutionReportsRoute: AppExecutionReportsRoute,
  AppExposureRoute: AppExposureRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppIpoRoute: AppIpoRoute,
  AppKillSwitchRoute: AppKillSwitchRoute,
  AppLiveRoute: AppLiveRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppScannerRoute: AppScannerRoute,
  AppStrategiesRoute: AppStrategiesRoute,
  AppSupportRoute: AppSupportRoute,
  AppTradeJournalRoute: AppTradeJournalRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
